# This flake was initially generated by fh, the CLI for FlakeHub (version 0.1.18)
{

  inputs = {
    flake-schemas.url = "https://flakehub.com/f/DeterminateSystems/flake-schemas/*";

    nixpkgs.url = "https://flakehub.com/f/NixOS/nixpkgs/*";
  };

  outputs =
    {
      self,
      flake-schemas,
      nixpkgs,
    }:
    let

      supportedSystems = [ "x86_64-linux" ];
      forEachSupportedSystem =
        f:
        nixpkgs.lib.genAttrs supportedSystems (
          system:
          f {
            pkgs = import nixpkgs { inherit system; };
          }
        );
    in
    {

      schemas = flake-schemas.schemas;

      devShells = forEachSupportedSystem (
        { pkgs }:
        {
          default = pkgs.mkShell {

            packages = with pkgs; [
              nixpkgs-fmt
              qmk
              just

              python3
              python3Packages.pip

              inkscape
            ];

            shellHook = ''
              if [ ! -d .venv ]; then
                python3 -m venv .venv
              fi

              source .venv/bin/activate

              if ! pip list | grep -q "keymap-drawer"; then
                pip install keymap-drawer
              fi

              if [ -f $HOME/qmk_firmware/requirements.txt ]; then
                pip install -r $HOME/qmk_firmware/requirements.txt
              fi
            '';
          };
        }
      );
    };
}
