COMBO_ENABLE = yes
LTO_ENABLE = yes
MOUSEKEY_ENABLE = yes
POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = navigator_trackball
LAYER_LOCK_ENABLE = yes
CONSOLE_ENABLE = no
AUTO_SHIFT_ENABLE = yes

KEYBOARD_SHARED_EP = yes

# Reduce firmware size
RAW_ENABLE = no
MAGIC_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
BOOTMAGIC_ENABLE = no
CAPS_WORD_ENABLE = no
SWAP_HANDS_ENABLE = no
SEND_STRING_ENABLE = no
