COMBO_ENABLE = yes
LTO_ENABLE = yes
MOUSEKEY_ENABLE = yes
POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = navigator_trackball
LAYER_LOCK_ENABLE = yes
CONSOLE_ENABLE = yes
AUTO_SHIFT_ENABLE = yes

VIA_ENABLE = no
VIAL_ENABLE = no
KEYBOARD_SHARED_EP = yes
